name: CI

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        pip install -r tests/requirements.txt  # Install test dependencies from requirements.txt

    - name: Run Black
      run: |
        black .  # Format all Python files in the repository
        git diff --exit-code || (echo "Black formatting required." && exit 1)

    - name: Run pytest
      run: |
        pytest  # Run your pytest tests

    - name: Complete PR Check
      run: |
        # This step is optional but can be used to provide a status check comment on the PR
        echo "Black and pytest checks passed."
